name: Sonar + Github CI + Zap

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy-gh-pages:
    runs-on: ubuntu-latest
    needs: build-test-sonarcloud
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular
        run: |
          echo "export const environment = {
            production: true,
            GATEWAY: '${{ secrets.GATEWAY_API }}',
            HES: '${{ secrets.HES_API }}',
            TELEMETRY: '${{ secrets.TELEMETRY_API }}',
            COMMAND: '${{ secrets.COMMAND_API }}',
            TENANT_ID: '${{ secrets.TENANT }}',
            TOKEN: '${{ secrets.TOKEN }}'
          };" > src/environments/environment.prod.ts
          npm run build -- --configuration production --base-href="/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./dist/MDMS/browser/
          keep_files: true
          force_orphan: true

  zap-scan:
    runs-on: ubuntu-latest
    needs: deploy-gh-pages
    name: ZAP Baseline Scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: main

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          token: ${{ secrets.GH_PAT }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://aabidrahman001.github.io/MDMS/'
          rules_file_name: 'zap-rules.tsv'
          cmd_options: '-a'


      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html
